project_id = "xrmkhmpgkkyeiwmgmyxw"

[functions.generate-starter-pack]
verify_jwt = false

[functions.manage-api-settings]
verify_jwt = false

[functions.get-creators]
verify_jwt = false

[functions.get-creator-data]
verify_jwt = false

[functions.save-starter-pack]
verify_jwt = false

[functions.get-starter-packs]
verify_jwt = false

[functions.update-starter-pack-status]
verify_jwt = false